[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/backend"]

[project]
name = "hdb-resale-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "fastapi[standard]>=0.141.1,<0.142",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "nanoid>=2.0.0",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
    "psycopg2>=2.9.12",
    "pydantic>=2.13.4",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "scikit-learn>=1.9.0",
    "sqlalchemy>=2.0.52",
    "statsmodels>=0.14.6",
]

[tool.fastapi]
entrypoint = "backend.main:app"

[pytest]
addopts = ["--import-mode=importlib"]
